export function isClearlyOffTopic(message: string) {
    const normalized = message.toLowerCase()

    const travelOrSkysirvSignals = [
        "skysirv",
        "flight",
        "flights",
        "fare",
        "fares",
        "route",
        "routes",
        "watchlist",
        "saved flight",
        "saved flights",
        "track",
        "tracking",
        "booking",
        "book",
        "airport",
        "airports",
        "airline",
        "airlines",
        "ticket",
        "tickets",
        "trip",
        "trips",
        "travel",
        "traveler",
        "travelling",
        "traveling",
        "vacation",
        "holiday",
        "destination",
        "destinations",
        "itinerary",
        "itineraries",
        "layover",
        "layovers",
        "connection",
        "connections",
        "terminal",
        "terminals",
        "gate",
        "gates",
        "lounge",
        "lounges",
        "baggage",
        "bags",
        "carry-on",
        "carry on",
        "packing",
        "passport",
        "visa",
        "customs",
        "immigration",
        "hotel",
        "hotels",
        "rental car",
        "car rental",
        "family trip",
        "business trip",
        "plan",
        "planning",
        "subscription",
        "lucy",
        "skyscore",
        "price",
        "prices",
        "pro",
        "free",
        "business",
    ]

    const offTopicSignals = [
        "cook",
        "dinner",
        "recipe",
        "meal",
        "poem",
        "joke",
        "coding",
        "code",
        "homework",
        "math",
        "medical",
        "doctor",
        "legal",
        "lawyer",
        "financial advice",
        "relationship",
        "sports",
        "politics",
        "movie",
        "song",
    ]

    const hasTravelOrSkysirvSignal = travelOrSkysirvSignals.some((signal) =>
        normalized.includes(signal),
    )

    const hasOffTopicSignal = offTopicSignals.some((signal) =>
        normalized.includes(signal),
    )

    return hasOffTopicSignal && !hasTravelOrSkysirvSignal
}