export type SkysirvLiveAirportClass =
  | "major_commercial"
  | "regional_commercial"
  | "executive"
export type SkysirvLiveGlobalRegion =
  | "north_america"
  | "central_america_caribbean"
  | "south_america"
  | "europe"
  | "middle_east"
  | "africa"
  | "asia"
  | "oceania"
export type SkysirvLiveAirportProvider =
  | "faa"
  | "cirium"
  | "flightaware"
export type SkysirvLiveAirportCatalogEntry = {
  iataCode: string
  icaoCode: string | null
  faaLid: string | null
  name: string
  city: string
  country: string
  countryCode: string
  region: string | null
  displayName: string
  globalRegion: SkysirvLiveGlobalRegion
  airportClass: SkysirvLiveAirportClass
  latitude: number
  longitude: number
  priorityRank: number
  isSkysirvLiveEnabled: boolean
  supportsFaa: boolean
  supportsCirium: boolean
  supportsFlightAware: boolean
}
export type SkysirvLiveAirportCatalogFilters = {
  includeDisabled?: boolean
  globalRegions?: SkysirvLiveGlobalRegion[]
  airportClasses?: SkysirvLiveAirportClass[]
  countryCodes?: string[]
  providers?: SkysirvLiveAirportProvider[]
}
const northAmericaAirports: SkysirvLiveAirportCatalogEntry[] = [
  // North America - United States and Canada
  { iataCode: "ABQ", icaoCode: null, faaLid: null, name: "Albuquerque International Sunport", city: "Albuquerque", country: "United States", countryCode: "US", region: "NM", displayName: "Albuquerque International Sunport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 35.0402, longitude: -106.6092, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ALB", icaoCode: null, faaLid: null, name: "Albany International", city: "Albany", country: "United States", countryCode: "US", region: "NY", displayName: "Albany Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 42.7483, longitude: -73.8017, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ANC", icaoCode: null, faaLid: null, name: "Ted Stevens Anchorage International", city: "Anchorage", country: "United States", countryCode: "US", region: "AK", displayName: "Ted Stevens Anchorage Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 61.1744, longitude: -149.9964, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ATL", icaoCode: null, faaLid: null, name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "United States", countryCode: "US", region: "GA", displayName: "Hartsfield-Jackson Atlanta Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 33.6407, longitude: -84.4277, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "AUS", icaoCode: null, faaLid: null, name: "Austin-Bergstrom International", city: "Austin", country: "United States", countryCode: "US", region: "TX", displayName: "Austin-Bergstrom Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 30.1975, longitude: -97.6664, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "AVL", icaoCode: null, faaLid: null, name: "Asheville Regional", city: "Asheville", country: "United States", countryCode: "US", region: "NC", displayName: "Asheville Regional Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 35.4362, longitude: -82.5418, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BDL", icaoCode: null, faaLid: null, name: "Bradley International", city: "Hartford", country: "United States", countryCode: "US", region: "CT", displayName: "Bradley Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 41.9389, longitude: -72.6832, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BNA", icaoCode: null, faaLid: null, name: "Nashville International", city: "Nashville", country: "United States", countryCode: "US", region: "TN", displayName: "Nashville Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 36.1263, longitude: -86.6774, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BOI", icaoCode: null, faaLid: null, name: "Boise Airport", city: "Boise", country: "United States", countryCode: "US", region: "ID", displayName: "Boise Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 43.5644, longitude: -116.2228, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BOS", icaoCode: null, faaLid: null, name: "Boston Logan International", city: "Boston", country: "United States", countryCode: "US", region: "MA", displayName: "Boston Logan Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 42.3656, longitude: -71.0096, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BUF", icaoCode: null, faaLid: null, name: "Buffalo Niagara International", city: "Buffalo", country: "United States", countryCode: "US", region: "NY", displayName: "Buffalo Niagara Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 42.9405, longitude: -78.7322, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BUR", icaoCode: null, faaLid: null, name: "Hollywood Burbank", city: "Burbank", country: "United States", countryCode: "US", region: "CA", displayName: "Hollywood Burbank Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 34.2007, longitude: -118.3587, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BWI", icaoCode: null, faaLid: null, name: "Baltimore/Washington International Thurgood Marshall", city: "Baltimore", country: "United States", countryCode: "US", region: "MD", displayName: "Baltimore/Washington Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 39.1774, longitude: -76.6684, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CHS", icaoCode: null, faaLid: null, name: "Charleston International", city: "Charleston", country: "United States", countryCode: "US", region: "SC", displayName: "Charleston Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 32.8986, longitude: -80.0405, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CLE", icaoCode: null, faaLid: null, name: "Cleveland Hopkins International", city: "Cleveland", country: "United States", countryCode: "US", region: "OH", displayName: "Cleveland Hopkins Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 41.4117, longitude: -81.8498, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CLT", icaoCode: null, faaLid: null, name: "Charlotte Douglas International", city: "Charlotte", country: "United States", countryCode: "US", region: "NC", displayName: "Charlotte Douglas Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 35.214, longitude: -80.9431, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CMH", icaoCode: null, faaLid: null, name: "John Glenn Columbus International", city: "Columbus", country: "United States", countryCode: "US", region: "OH", displayName: "John Glenn Columbus Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 39.998, longitude: -82.8919, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CVG", icaoCode: null, faaLid: null, name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", country: "United States", countryCode: "US", region: "KY", displayName: "Cincinnati/Northern Kentucky Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 39.0488, longitude: -84.6678, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DAL", icaoCode: null, faaLid: null, name: "Dallas Love Field", city: "Dallas", country: "United States", countryCode: "US", region: "TX", displayName: "Dallas Love Field", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 32.8471, longitude: -96.8518, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DCA", icaoCode: null, faaLid: null, name: "Ronald Reagan Washington National", city: "Washington", country: "United States", countryCode: "US", region: "DC", displayName: "Reagan National Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 38.8521, longitude: -77.0377, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DEN", icaoCode: null, faaLid: null, name: "Denver International", city: "Denver", country: "United States", countryCode: "US", region: "CO", displayName: "Denver Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 39.8561, longitude: -104.6737, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DFW", icaoCode: null, faaLid: null, name: "Dallas Fort Worth International", city: "Dallas", country: "United States", countryCode: "US", region: "TX", displayName: "Dallas Fort Worth Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 32.8998, longitude: -97.0403, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DTW", icaoCode: null, faaLid: null, name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "United States", countryCode: "US", region: "MI", displayName: "Metropolitan Wayne County Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 42.2162, longitude: -83.3554, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "EGE", icaoCode: null, faaLid: null, name: "Eagle County Regional", city: "Vail", country: "United States", countryCode: "US", region: "CO", displayName: "Eagle County Regional Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 39.6426, longitude: -106.9177, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "EWR", icaoCode: null, faaLid: null, name: "Newark Liberty International", city: "Newark", country: "United States", countryCode: "US", region: "NJ", displayName: "Newark Liberty Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 40.6895, longitude: -74.1745, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "FAT", icaoCode: null, faaLid: null, name: "Fresno Yosemite International", city: "Fresno", country: "United States", countryCode: "US", region: "CA", displayName: "Fresno Yosemite Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 36.7762, longitude: -119.7181, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "FLL", icaoCode: null, faaLid: null, name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "United States", countryCode: "US", region: "FL", displayName: "Fort Lauderdale-Hollywood Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 26.0726, longitude: -80.1527, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GEG", icaoCode: null, faaLid: null, name: "Spokane International", city: "Spokane", country: "United States", countryCode: "US", region: "WA", displayName: "Spokane Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 47.6199, longitude: -117.5338, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GRR", icaoCode: null, faaLid: null, name: "Gerald R. Ford International", city: "Grand Rapids", country: "United States", countryCode: "US", region: "MI", displayName: "Gerald R. Ford Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 42.8808, longitude: -85.5228, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HNL", icaoCode: null, faaLid: null, name: "Daniel K. Inouye International", city: "Honolulu", country: "United States", countryCode: "US", region: "HI", displayName: "Daniel K. Inouye Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 21.3187, longitude: -157.9225, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HOU", icaoCode: null, faaLid: null, name: "William P. Hobby", city: "Houston", country: "United States", countryCode: "US", region: "TX", displayName: "William P. Hobby Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 29.6454, longitude: -95.2789, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HPN", icaoCode: null, faaLid: null, name: "Westchester County", city: "White Plains", country: "United States", countryCode: "US", region: "NY", displayName: "Westchester County Airport", globalRegion: "north_america", airportClass: "executive", latitude: 41.0669, longitude: -73.7076, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "IAD", icaoCode: null, faaLid: null, name: "Washington Dulles International", city: "Washington", country: "United States", countryCode: "US", region: "VA", displayName: "Washington Dulles Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 38.9531, longitude: -77.4565, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "IAH", icaoCode: null, faaLid: null, name: "George Bush Intercontinental", city: "Houston", country: "United States", countryCode: "US", region: "TX", displayName: "George Bush Intercontinental Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 29.9844, longitude: -95.3414, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "IND", icaoCode: null, faaLid: null, name: "Indianapolis International", city: "Indianapolis", country: "United States", countryCode: "US", region: "IN", displayName: "Indianapolis Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 39.7173, longitude: -86.2944, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ISP", icaoCode: null, faaLid: null, name: "Long Island MacArthur", city: "Islip", country: "United States", countryCode: "US", region: "NY", displayName: "Long Island MacArthur Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 40.7952, longitude: -73.1002, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "JAX", icaoCode: null, faaLid: null, name: "Jacksonville International", city: "Jacksonville", country: "United States", countryCode: "US", region: "FL", displayName: "Jacksonville Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 30.4941, longitude: -81.6879, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "JFK", icaoCode: null, faaLid: null, name: "John F. Kennedy International", city: "New York", country: "United States", countryCode: "US", region: "NY", displayName: "John F. Kennedy Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 40.6413, longitude: -73.7781, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "KOA", icaoCode: null, faaLid: null, name: "Ellison Onizuka Kona International", city: "Kailua-Kona", country: "United States", countryCode: "US", region: "HI", displayName: "Kona Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 19.7388, longitude: -156.0456, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LAS", icaoCode: null, faaLid: null, name: "Harry Reid International", city: "Las Vegas", country: "United States", countryCode: "US", region: "NV", displayName: "Harry Reid Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 36.084, longitude: -115.1537, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LAX", icaoCode: null, faaLid: null, name: "Los Angeles International", city: "Los Angeles", country: "United States", countryCode: "US", region: "CA", displayName: "Los Angeles Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 33.9416, longitude: -118.4085, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LGA", icaoCode: null, faaLid: null, name: "LaGuardia", city: "New York", country: "United States", countryCode: "US", region: "NY", displayName: "LaGuardia Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 40.7769, longitude: -73.874, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LGB", icaoCode: null, faaLid: null, name: "Long Beach Airport", city: "Long Beach", country: "United States", countryCode: "US", region: "CA", displayName: "Long Beach Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 33.8177, longitude: -118.1516, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LIH", icaoCode: null, faaLid: null, name: "Lihue Airport", city: "Lihue", country: "United States", countryCode: "US", region: "HI", displayName: "Lihue Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 21.976, longitude: -159.3389, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MCI", icaoCode: null, faaLid: null, name: "Kansas City International", city: "Kansas City", country: "United States", countryCode: "US", region: "MO", displayName: "Kansas City Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 39.2976, longitude: -94.7139, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MCO", icaoCode: null, faaLid: null, name: "Orlando International", city: "Orlando", country: "United States", countryCode: "US", region: "FL", displayName: "Orlando Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 28.4312, longitude: -81.3081, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MDW", icaoCode: null, faaLid: null, name: "Chicago Midway International", city: "Chicago", country: "United States", countryCode: "US", region: "IL", displayName: "Chicago Midway Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 41.7868, longitude: -87.7522, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MEM", icaoCode: null, faaLid: null, name: "Memphis International", city: "Memphis", country: "United States", countryCode: "US", region: "TN", displayName: "Memphis Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 35.0424, longitude: -89.9767, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MHT", icaoCode: "KMHT", faaLid: "MHT", name: "Manchester Boston Regional", city: "Manchester", country: "United States", countryCode: "US", region: "NH", displayName: "Manchester Boston Regional Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 42.9328056, longitude: -71.43575, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MIA", icaoCode: null, faaLid: null, name: "Miami International", city: "Miami", country: "United States", countryCode: "US", region: "FL", displayName: "Miami Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 25.7959, longitude: -80.287, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MKE", icaoCode: null, faaLid: null, name: "Milwaukee Mitchell International", city: "Milwaukee", country: "United States", countryCode: "US", region: "WI", displayName: "Milwaukee Mitchell Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 42.9472, longitude: -87.8966, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MSP", icaoCode: null, faaLid: null, name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "United States", countryCode: "US", region: "MN", displayName: "Minneapolis-Saint Paul Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 44.8848, longitude: -93.2223, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MSY", icaoCode: null, faaLid: null, name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "United States", countryCode: "US", region: "LA", displayName: "Louis Armstrong New Orleans Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 29.9934, longitude: -90.258, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MYR", icaoCode: null, faaLid: null, name: "Myrtle Beach International", city: "Myrtle Beach", country: "United States", countryCode: "US", region: "SC", displayName: "Myrtle Beach Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 33.6797, longitude: -78.9283, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "OAK", icaoCode: null, faaLid: null, name: "Oakland International", city: "Oakland", country: "United States", countryCode: "US", region: "CA", displayName: "Oakland Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 37.7126, longitude: -122.2197, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "OMA", icaoCode: null, faaLid: null, name: "Eppley Airfield", city: "Omaha", country: "United States", countryCode: "US", region: "NE", displayName: "Eppley Airfield", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 41.3032, longitude: -95.8941, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ONT", icaoCode: null, faaLid: null, name: "Ontario International", city: "Ontario", country: "United States", countryCode: "US", region: "CA", displayName: "Ontario Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 34.056, longitude: -117.6012, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ORD", icaoCode: null, faaLid: null, name: "O'Hare International", city: "Chicago", country: "United States", countryCode: "US", region: "IL", displayName: "O'Hare Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 41.9742, longitude: -87.9073, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ORF", icaoCode: null, faaLid: null, name: "Norfolk International", city: "Norfolk", country: "United States", countryCode: "US", region: "VA", displayName: "Norfolk Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 36.8946, longitude: -76.2012, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PBI", icaoCode: null, faaLid: null, name: "Palm Beach International", city: "West Palm Beach", country: "United States", countryCode: "US", region: "FL", displayName: "Palm Beach Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 26.6832, longitude: -80.0956, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PDX", icaoCode: null, faaLid: null, name: "Portland International", city: "Portland", country: "United States", countryCode: "US", region: "OR", displayName: "Portland Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 45.5898, longitude: -122.5951, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PHL", icaoCode: null, faaLid: null, name: "Philadelphia International", city: "Philadelphia", country: "United States", countryCode: "US", region: "PA", displayName: "Philadelphia Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 39.8744, longitude: -75.2424, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PHX", icaoCode: null, faaLid: null, name: "Phoenix Sky Harbor International", city: "Phoenix", country: "United States", countryCode: "US", region: "AZ", displayName: "Phoenix Sky Harbor Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 33.4352, longitude: -112.0101, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PIT", icaoCode: null, faaLid: null, name: "Pittsburgh International", city: "Pittsburgh", country: "United States", countryCode: "US", region: "PA", displayName: "Pittsburgh Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 40.4915, longitude: -80.2329, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PNS", icaoCode: null, faaLid: null, name: "Pensacola International", city: "Pensacola", country: "United States", countryCode: "US", region: "FL", displayName: "Pensacola Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 30.4734, longitude: -87.1866, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PSP", icaoCode: null, faaLid: null, name: "Palm Springs International", city: "Palm Springs", country: "United States", countryCode: "US", region: "CA", displayName: "Palm Springs Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 33.8297, longitude: -116.5067, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PVD", icaoCode: null, faaLid: null, name: "Rhode Island T. F. Green International", city: "Providence", country: "United States", countryCode: "US", region: "RI", displayName: "T. F. Green Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 41.724, longitude: -71.4282, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PWM", icaoCode: "KPWM", faaLid: "PWM", name: "Portland International Jetport", city: "Portland", country: "United States", countryCode: "US", region: "ME", displayName: "Portland International Jetport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 43.6456435, longitude: -70.3086164, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "RDU", icaoCode: null, faaLid: null, name: "Raleigh-Durham International", city: "Raleigh-Durham", country: "United States", countryCode: "US", region: "NC", displayName: "Raleigh-Durham Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 35.8776, longitude: -78.7875, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "RIC", icaoCode: null, faaLid: null, name: "Richmond International", city: "Richmond", country: "United States", countryCode: "US", region: "VA", displayName: "Richmond Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 37.5052, longitude: -77.3197, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "RNO", icaoCode: null, faaLid: null, name: "Reno-Tahoe International", city: "Reno", country: "United States", countryCode: "US", region: "NV", displayName: "Reno-Tahoe Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 39.4991, longitude: -119.7681, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ROC", icaoCode: null, faaLid: null, name: "Frederick Douglass Greater Rochester International", city: "Rochester", country: "United States", countryCode: "US", region: "NY", displayName: "Greater Rochester Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 43.1189, longitude: -77.6724, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "RSW", icaoCode: null, faaLid: null, name: "Southwest Florida International", city: "Fort Myers", country: "United States", countryCode: "US", region: "FL", displayName: "Southwest Florida Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 26.5362, longitude: -81.7552, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SAN", icaoCode: null, faaLid: null, name: "San Diego International", city: "San Diego", country: "United States", countryCode: "US", region: "CA", displayName: "San Diego Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 32.7338, longitude: -117.1933, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SAT", icaoCode: null, faaLid: null, name: "San Antonio International", city: "San Antonio", country: "United States", countryCode: "US", region: "TX", displayName: "San Antonio Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 29.5337, longitude: -98.4698, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SBA", icaoCode: null, faaLid: null, name: "Santa Barbara Municipal", city: "Santa Barbara", country: "United States", countryCode: "US", region: "CA", displayName: "Santa Barbara Municipal Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 34.4262, longitude: -119.8404, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SDF", icaoCode: null, faaLid: null, name: "Louisville Muhammad Ali International", city: "Louisville", country: "United States", countryCode: "US", region: "KY", displayName: "Louisville Muhammad Ali Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 38.1744, longitude: -85.736, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SEA", icaoCode: null, faaLid: null, name: "Seattle-Tacoma International", city: "Seattle", country: "United States", countryCode: "US", region: "WA", displayName: "Seattle-Tacoma Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 47.4502, longitude: -122.3088, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SFO", icaoCode: null, faaLid: null, name: "San Francisco International", city: "San Francisco", country: "United States", countryCode: "US", region: "CA", displayName: "San Francisco Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 37.6213, longitude: -122.379, priorityRank: 1, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SJC", icaoCode: null, faaLid: null, name: "San Jose Mineta International", city: "San Jose", country: "United States", countryCode: "US", region: "CA", displayName: "San Jose Mineta Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 37.3639, longitude: -121.9289, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SLC", icaoCode: null, faaLid: null, name: "Salt Lake City International", city: "Salt Lake City", country: "United States", countryCode: "US", region: "UT", displayName: "Salt Lake City Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 40.7899, longitude: -111.9791, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SMF", icaoCode: null, faaLid: null, name: "Sacramento International", city: "Sacramento", country: "United States", countryCode: "US", region: "CA", displayName: "Sacramento Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 38.6954, longitude: -121.5908, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SNA", icaoCode: null, faaLid: null, name: "John Wayne Airport", city: "Orange County", country: "United States", countryCode: "US", region: "CA", displayName: "John Wayne Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 33.6757, longitude: -117.8682, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SRQ", icaoCode: null, faaLid: null, name: "Sarasota Bradenton International", city: "Sarasota", country: "United States", countryCode: "US", region: "FL", displayName: "Sarasota Bradenton Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 27.3954, longitude: -82.5544, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "STL", icaoCode: null, faaLid: null, name: "St. Louis Lambert International", city: "St. Louis", country: "United States", countryCode: "US", region: "MO", displayName: "St. Louis Lambert Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 38.7487, longitude: -90.37, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SYR", icaoCode: null, faaLid: null, name: "Syracuse Hancock International", city: "Syracuse", country: "United States", countryCode: "US", region: "NY", displayName: "Syracuse Hancock Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 43.1112, longitude: -76.1063, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "TEB", icaoCode: null, faaLid: null, name: "Teterboro Airport", city: "Teterboro", country: "United States", countryCode: "US", region: "NJ", displayName: "Teterboro Airport", globalRegion: "north_america", airportClass: "executive", latitude: 40.8501, longitude: -74.0608, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "TPA", icaoCode: null, faaLid: null, name: "Tampa International", city: "Tampa", country: "United States", countryCode: "US", region: "FL", displayName: "Tampa Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 27.9755, longitude: -82.5332, priorityRank: 2, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "TUL", icaoCode: null, faaLid: null, name: "Tulsa International", city: "Tulsa", country: "United States", countryCode: "US", region: "OK", displayName: "Tulsa Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 36.1984, longitude: -95.8881, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "TUS", icaoCode: null, faaLid: null, name: "Tucson International", city: "Tucson", country: "United States", countryCode: "US", region: "AZ", displayName: "Tucson Intl Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 32.1161, longitude: -110.941, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "VPS", icaoCode: null, faaLid: null, name: "Destin-Fort Walton Beach Airport", city: "Destin-Fort Walton Beach", country: "United States", countryCode: "US", region: "FL", displayName: "Destin-Fort Walton Beach Airport", globalRegion: "north_america", airportClass: "regional_commercial", latitude: 30.4832, longitude: -86.5254, priorityRank: 4, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "YUL", icaoCode: null, faaLid: null, name: "Montreal-Trudeau International", city: "Montreal", country: "Canada", countryCode: "CA", region: null, displayName: "Montreal-Trudeau Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 45.4706, longitude: -73.7408, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "YVR", icaoCode: null, faaLid: null, name: "Vancouver International", city: "Vancouver", country: "Canada", countryCode: "CA", region: null, displayName: "Vancouver Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 49.1967, longitude: -123.1815, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "YYC", icaoCode: null, faaLid: null, name: "Calgary International", city: "Calgary", country: "Canada", countryCode: "CA", region: null, displayName: "Calgary Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 51.1215, longitude: -114.0076, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "YYZ", icaoCode: null, faaLid: null, name: "Toronto Pearson International", city: "Toronto", country: "Canada", countryCode: "CA", region: null, displayName: "Toronto Pearson Intl Airport", globalRegion: "north_america", airportClass: "major_commercial", latitude: 43.6777, longitude: -79.6248, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const mexicoCentralAmericaCaribbeanAirports: SkysirvLiveAirportCatalogEntry[] = [
  // Mexico, Central America, and Caribbean
  { iataCode: "SJU", icaoCode: null, faaLid: null, name: "Luis Munoz Marin International", city: "San Juan", country: "United States", countryCode: "US", region: "PR", displayName: "Luis Munoz Marin Intl Airport", globalRegion: "central_america_caribbean", airportClass: "regional_commercial", latitude: 18.4394, longitude: -66.0018, priorityRank: 3, isSkysirvLiveEnabled: true, supportsFaa: true, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CUN", icaoCode: null, faaLid: null, name: "Cancun International", city: "Cancun", country: "Mexico", countryCode: "MX", region: null, displayName: "Cancun Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 21.0365, longitude: -86.8771, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GDL", icaoCode: null, faaLid: null, name: "Guadalajara International", city: "Guadalajara", country: "Mexico", countryCode: "MX", region: null, displayName: "Guadalajara Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 20.5218, longitude: -103.3112, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GUA", icaoCode: null, faaLid: null, name: "La Aurora International", city: "Guatemala City", country: "Guatemala", countryCode: "GT", region: null, displayName: "La Aurora Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 14.5833, longitude: -90.5275, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MEX", icaoCode: null, faaLid: null, name: "Benito Juarez International", city: "Mexico City", country: "Mexico", countryCode: "MX", region: null, displayName: "Benito Juarez Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 19.4361, longitude: -99.0719, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MTY", icaoCode: null, faaLid: null, name: "Monterrey International", city: "Monterrey", country: "Mexico", countryCode: "MX", region: null, displayName: "Monterrey Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 25.7785, longitude: -100.107, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PTY", icaoCode: null, faaLid: null, name: "Tocumen International", city: "Panama City", country: "Panama", countryCode: "PA", region: null, displayName: "Tocumen Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 9.0714, longitude: -79.3835, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SAL", icaoCode: null, faaLid: null, name: "El Salvador International", city: "San Salvador", country: "El Salvador", countryCode: "SV", region: null, displayName: "El Salvador Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 13.4409, longitude: -89.0557, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SJO", icaoCode: null, faaLid: null, name: "Juan Santamaria International", city: "San Jose", country: "Costa Rica", countryCode: "CR", region: null, displayName: "Juan Santamaria Intl Airport", globalRegion: "central_america_caribbean", airportClass: "major_commercial", latitude: 9.9939, longitude: -84.2088, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const southAmericaAirports: SkysirvLiveAirportCatalogEntry[] = [
  // South America
  { iataCode: "BOG", icaoCode: null, faaLid: null, name: "El Dorado International", city: "Bogota", country: "Colombia", countryCode: "CO", region: null, displayName: "El Dorado Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: 4.7016, longitude: -74.1469, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CTG", icaoCode: null, faaLid: null, name: "Rafael Nunez International", city: "Cartagena", country: "Colombia", countryCode: "CO", region: null, displayName: "Rafael Nunez Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: 10.4424, longitude: -75.513, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CUZ", icaoCode: null, faaLid: null, name: "Alejandro Velasco Astete International", city: "Cusco", country: "Peru", countryCode: "PE", region: null, displayName: "Alejandro Velasco Astete Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -13.5357, longitude: -71.9388, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LIM", icaoCode: null, faaLid: null, name: "Jorge Chavez International", city: "Lima", country: "Peru", countryCode: "PE", region: null, displayName: "Jorge Chavez Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -12.0219, longitude: -77.1143, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MDE", icaoCode: null, faaLid: null, name: "Jose Maria Cordova International", city: "Medellin", country: "Colombia", countryCode: "CO", region: null, displayName: "Jose Maria Cordova Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: 6.1645, longitude: -75.4231, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CBB", icaoCode: null, faaLid: null, name: "Jorge Wilstermann International", city: "Cochabamba", country: "Bolivia", countryCode: "BO", region: null, displayName: "Jorge Wilstermann Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -17.4211, longitude: -66.1771, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LPB", icaoCode: null, faaLid: null, name: "El Alto International", city: "La Paz", country: "Bolivia", countryCode: "BO", region: null, displayName: "El Alto Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -16.5133, longitude: -68.1923, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "VVI", icaoCode: null, faaLid: null, name: "Viru Viru International", city: "Santa Cruz", country: "Bolivia", countryCode: "BO", region: null, displayName: "Viru Viru Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -17.6448, longitude: -63.1354, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "AEP", icaoCode: null, faaLid: null, name: "Jorge Newbery Airfield", city: "Buenos Aires", country: "Argentina", countryCode: "AR", region: null, displayName: "Jorge Newbery Airfield", globalRegion: "south_america", airportClass: "major_commercial", latitude: -34.5592, longitude: -58.4156, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BSB", icaoCode: null, faaLid: null, name: "Brasilia International", city: "Brasilia", country: "Brazil", countryCode: "BR", region: null, displayName: "Brasilia Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -15.8697, longitude: -47.9208, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CGH", icaoCode: null, faaLid: null, name: "Congonhas", city: "Sao Paulo", country: "Brazil", countryCode: "BR", region: null, displayName: "Congonhas Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -23.6267, longitude: -46.6554, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "COR", icaoCode: null, faaLid: null, name: "Ingeniero Aeronautico Ambrosio Taravella", city: "Cordoba", country: "Argentina", countryCode: "AR", region: null, displayName: "Ingeniero Ambrosio Taravella Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -31.31, longitude: -64.208, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "EZE", icaoCode: null, faaLid: null, name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina", countryCode: "AR", region: null, displayName: "Ministro Pistarini (Ezeiza) Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -34.8222, longitude: -58.5358, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GIG", icaoCode: null, faaLid: null, name: "Galeao International", city: "Rio de Janeiro", country: "Brazil", countryCode: "BR", region: null, displayName: "Galeao Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -22.809999, longitude: -43.250557, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GRU", icaoCode: null, faaLid: null, name: "Sao Paulo-Guarulhos International", city: "Sao Paulo", country: "Brazil", countryCode: "BR", region: null, displayName: "Sao Paulo-Guarulhos Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -23.4356, longitude: -46.4731, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "IPC", icaoCode: null, faaLid: null, name: "Mataveri International", city: "Easter Island", country: "Chile", countryCode: "CL", region: null, displayName: "Mataveri Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -27.1648, longitude: -109.4218, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SCL", icaoCode: null, faaLid: null, name: "Arturo Merino Benitez International", city: "Santiago", country: "Chile", countryCode: "CL", region: null, displayName: "Arturo Merino Benitez Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -33.3928, longitude: -70.7858, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SDU", icaoCode: null, faaLid: null, name: "Santos Dumont", city: "Rio de Janeiro", country: "Brazil", countryCode: "BR", region: null, displayName: "Santos Dumont Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -22.91, longitude: -43.1631, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SSA", icaoCode: null, faaLid: null, name: "Salvador International", city: "Salvador", country: "Brazil", countryCode: "BR", region: null, displayName: "Salvador Intl Airport", globalRegion: "south_america", airportClass: "major_commercial", latitude: -12.9086, longitude: -38.3225, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const europeAirports: SkysirvLiveAirportCatalogEntry[] = [
  // Europe
  { iataCode: "EDI", icaoCode: null, faaLid: null, name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", countryCode: "GB", region: null, displayName: "Edinburgh Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 55.95, longitude: -3.3725, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LCY", icaoCode: null, faaLid: null, name: "London City", city: "London", country: "United Kingdom", countryCode: "GB", region: null, displayName: "London City Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 51.5053, longitude: 0.0553, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LGW", icaoCode: null, faaLid: null, name: "Gatwick", city: "London", country: "United Kingdom", countryCode: "GB", region: null, displayName: "Gatwick Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 51.1537, longitude: -0.1821, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LHR", icaoCode: null, faaLid: null, name: "Heathrow", city: "London", country: "United Kingdom", countryCode: "GB", region: null, displayName: "Heathrow Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 51.47, longitude: -0.4543, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MAN", icaoCode: null, faaLid: null, name: "Manchester Airport", city: "Manchester", country: "United Kingdom", countryCode: "GB", region: null, displayName: "Manchester Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 53.365, longitude: -2.2726, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "AMS", icaoCode: null, faaLid: null, name: "Schiphol", city: "Amsterdam", country: "Netherlands", countryCode: "NL", region: null, displayName: "Schiphol Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 52.3105, longitude: 4.7683, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ARN", icaoCode: null, faaLid: null, name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", countryCode: "SE", region: null, displayName: "Stockholm Arlanda Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 59.6519, longitude: 17.9186, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ATH", icaoCode: null, faaLid: null, name: "Athens International", city: "Athens", country: "Greece", countryCode: "GR", region: null, displayName: "Athens Intl Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 37.9364, longitude: 23.9445, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BCN", icaoCode: null, faaLid: null, name: "Barcelona-El Prat", city: "Barcelona", country: "Spain", countryCode: "ES", region: null, displayName: "Barcelona-El Prat Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 41.2974, longitude: 2.0833, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BER", icaoCode: null, faaLid: null, name: "Berlin Brandenburg", city: "Berlin", country: "Germany", countryCode: "DE", region: null, displayName: "Berlin Brandenburg Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 52.3667, longitude: 13.5033, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BRU", icaoCode: null, faaLid: null, name: "Brussels Airport", city: "Brussels", country: "Belgium", countryCode: "BE", region: null, displayName: "Brussels Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 50.9014, longitude: 4.4844, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CDG", icaoCode: null, faaLid: null, name: "Charles de Gaulle", city: "Paris", country: "France", countryCode: "FR", region: null, displayName: "Charles de Gaulle Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 49.0097, longitude: 2.5479, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CPH", icaoCode: null, faaLid: null, name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", countryCode: "DK", region: null, displayName: "Copenhagen Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 55.6181, longitude: 12.6561, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DUB", icaoCode: null, faaLid: null, name: "Dublin Airport", city: "Dublin", country: "Ireland", countryCode: "IE", region: null, displayName: "Dublin Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 53.4213, longitude: -6.2701, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "FCO", icaoCode: null, faaLid: null, name: "Leonardo da Vinci Fiumicino", city: "Rome", country: "Italy", countryCode: "IT", region: null, displayName: "Leonardo da Vinci Fiumicino Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 41.8003, longitude: 12.2389, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "FRA", icaoCode: null, faaLid: null, name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", countryCode: "DE", region: null, displayName: "Frankfurt Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 50.0379, longitude: 8.5622, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GVA", icaoCode: null, faaLid: null, name: "Geneva Airport", city: "Geneva", country: "Switzerland", countryCode: "CH", region: null, displayName: "Geneva Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 46.2381, longitude: 6.1089, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HEL", icaoCode: null, faaLid: null, name: "Helsinki Airport", city: "Helsinki", country: "Finland", countryCode: "FI", region: null, displayName: "Helsinki Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 60.3172, longitude: 24.9633, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "IST", icaoCode: null, faaLid: null, name: "Istanbul Airport", city: "Istanbul", country: "Turkey", countryCode: "TR", region: null, displayName: "Istanbul Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 41.2753, longitude: 28.7519, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LIN", icaoCode: null, faaLid: null, name: "Linate", city: "Milan", country: "Italy", countryCode: "IT", region: null, displayName: "Linate Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 45.4451, longitude: 9.2767, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "LIS", icaoCode: null, faaLid: null, name: "Humberto Delgado", city: "Lisbon", country: "Portugal", countryCode: "PT", region: null, displayName: "Humberto Delgado Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 38.7742, longitude: -9.1342, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MAD", icaoCode: null, faaLid: null, name: "Adolfo Suarez Madrid-Barajas", city: "Madrid", country: "Spain", countryCode: "ES", region: null, displayName: "Adolfo Suarez Madrid-Barajas Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 40.4983, longitude: -3.5676, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MUC", icaoCode: null, faaLid: null, name: "Munich Airport", city: "Munich", country: "Germany", countryCode: "DE", region: null, displayName: "Munich Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 48.3538, longitude: 11.7861, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MXP", icaoCode: null, faaLid: null, name: "Milan Malpensa", city: "Milan", country: "Italy", countryCode: "IT", region: null, displayName: "Milan Malpensa Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 45.6306, longitude: 8.7281, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "NCE", icaoCode: null, faaLid: null, name: "Nice Cote d'Azur", city: "Nice", country: "France", countryCode: "FR", region: null, displayName: "Nice Cote d'Azur Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 43.6584, longitude: 7.2159, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "OPO", icaoCode: null, faaLid: null, name: "Francisco Sa Carneiro", city: "Porto", country: "Portugal", countryCode: "PT", region: null, displayName: "Francisco Sa Carneiro Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 41.2421, longitude: -8.6785, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ORY", icaoCode: null, faaLid: null, name: "Orly", city: "Paris", country: "France", countryCode: "FR", region: null, displayName: "Orly Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 48.7233, longitude: 2.3794, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "OSL", icaoCode: null, faaLid: null, name: "Oslo Gardermoen", city: "Oslo", country: "Norway", countryCode: "NO", region: null, displayName: "Oslo Gardermoen Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 60.1975, longitude: 11.1004, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PMI", icaoCode: null, faaLid: null, name: "Palma de Mallorca", city: "Palma", country: "Spain", countryCode: "ES", region: null, displayName: "Palma de Mallorca Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 39.5517, longitude: 2.7388, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "VCE", icaoCode: null, faaLid: null, name: "Marco Polo", city: "Venice", country: "Italy", countryCode: "IT", region: null, displayName: "Marco Polo Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 45.5053, longitude: 12.3519, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "VIE", icaoCode: null, faaLid: null, name: "Vienna International", city: "Vienna", country: "Austria", countryCode: "AT", region: null, displayName: "Vienna Intl Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 48.1103, longitude: 16.5697, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ZRH", icaoCode: null, faaLid: null, name: "Zurich Airport", city: "Zurich", country: "Switzerland", countryCode: "CH", region: null, displayName: "Zurich Airport", globalRegion: "europe", airportClass: "major_commercial", latitude: 47.4581, longitude: 8.5555, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const middleEastAirports: SkysirvLiveAirportCatalogEntry[] = [
  // Middle East
  { iataCode: "AUH", icaoCode: null, faaLid: null, name: "Zayed International", city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE", region: null, displayName: "Zayed Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 24.433, longitude: 54.6511, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CAI", icaoCode: null, faaLid: null, name: "Cairo International", city: "Cairo", country: "Egypt", countryCode: "EG", region: null, displayName: "Cairo Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 30.1219, longitude: 31.4056, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CMN", icaoCode: null, faaLid: null, name: "Mohammed V International", city: "Casablanca", country: "Morocco", countryCode: "MA", region: null, displayName: "Mohammed V Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 33.3675, longitude: -7.5899, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DOH", icaoCode: null, faaLid: null, name: "Hamad International", city: "Doha", country: "Qatar", countryCode: "QA", region: null, displayName: "Hamad Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 25.2731, longitude: 51.6081, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DXB", icaoCode: null, faaLid: null, name: "Dubai International", city: "Dubai", country: "United Arab Emirates", countryCode: "AE", region: null, displayName: "Dubai Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 25.2532, longitude: 55.3657, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "JED", icaoCode: null, faaLid: null, name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia", countryCode: "SA", region: null, displayName: "King Abdulaziz Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 21.6796, longitude: 39.1565, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "TLV", icaoCode: null, faaLid: null, name: "Ben Gurion International", city: "Tel Aviv-Yafo", country: "Israel", countryCode: "IL", region: null, displayName: "Ben Gurion Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 32.0114, longitude: 34.8867, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "KWI", icaoCode: null, faaLid: null, name: "Kuwait International", city: "Kuwait City", country: "Kuwait", countryCode: "KW", region: null, displayName: "Kuwait Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 29.2266, longitude: 47.9689, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BAH", icaoCode: null, faaLid: null, name: "Bahrain International", city: "Bahrain", country: "Bahrain", countryCode: "BH", region: null, displayName: "Bahrain Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 26.2708, longitude: 50.6336, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "RUH", icaoCode: null, faaLid: null, name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia", countryCode: "SA", region: null, displayName: "King Khalid Intl Airport", globalRegion: "middle_east", airportClass: "major_commercial", latitude: 24.9576, longitude: 46.6988, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const africaAirports: SkysirvLiveAirportCatalogEntry[] = [
  // Africa
  { iataCode: "ADD", icaoCode: null, faaLid: null, name: "Bole International", city: "Addis Ababa", country: "Ethiopia", countryCode: "ET", region: null, displayName: "Bole Intl Airport", globalRegion: "africa", airportClass: "major_commercial", latitude: 8.9779, longitude: 38.7993, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ALG", icaoCode: null, faaLid: null, name: "Houari Boumediene", city: "Algiers", country: "Algeria", countryCode: "DZ", region: null, displayName: "Houari Boumediene Airport", globalRegion: "africa", airportClass: "major_commercial", latitude: 36.691, longitude: 3.2154, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CPT", icaoCode: null, faaLid: null, name: "Cape Town International", city: "Cape Town", country: "South Africa", countryCode: "ZA", region: null, displayName: "Cape Town Intl Airport", globalRegion: "africa", airportClass: "major_commercial", latitude: -33.9715, longitude: 18.6021, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "JNB", icaoCode: null, faaLid: null, name: "O.R. Tambo International", city: "Johannesburg", country: "South Africa", countryCode: "ZA", region: null, displayName: "O.R. Tambo Intl Airport", globalRegion: "africa", airportClass: "major_commercial", latitude: -26.1337, longitude: 28.242, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "NBO", icaoCode: null, faaLid: null, name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya", countryCode: "KE", region: null, displayName: "Jomo Kenyatta Intl Airport", globalRegion: "africa", airportClass: "major_commercial", latitude: -1.3192, longitude: 36.9278, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "RAK", icaoCode: null, faaLid: null, name: "Marrakesh Menara", city: "Marrakesh", country: "Morocco", countryCode: "MA", region: null, displayName: "Marrakesh Menara Airport", globalRegion: "africa", airportClass: "major_commercial", latitude: 31.6069, longitude: -8.0363, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const asiaAirports: SkysirvLiveAirportCatalogEntry[] = [
  // Asia
  { iataCode: "BKK", icaoCode: null, faaLid: null, name: "Suvarnabhumi", city: "Bangkok", country: "Thailand", countryCode: "TH", region: null, displayName: "Suvarnabhumi Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 13.69, longitude: 100.7501, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BLR", icaoCode: null, faaLid: null, name: "Kempegowda International", city: "Bengaluru", country: "India", countryCode: "IN", region: null, displayName: "Kempegowda Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 13.1986, longitude: 77.7066, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BOM", icaoCode: null, faaLid: null, name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India", countryCode: "IN", region: null, displayName: "Chhatrapati Shivaji Maharaj Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 19.0896, longitude: 72.8656, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CAN", icaoCode: null, faaLid: null, name: "Baiyun International", city: "Guangzhou", country: "China", countryCode: "CN", region: null, displayName: "Baiyun Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 23.3924, longitude: 113.2988, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CGK", icaoCode: null, faaLid: null, name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia", countryCode: "ID", region: null, displayName: "Soekarno-Hatta Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: -6.1256, longitude: 106.6559, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "DEL", icaoCode: null, faaLid: null, name: "Indira Gandhi International", city: "Delhi", country: "India", countryCode: "IN", region: null, displayName: "Indira Gandhi Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 28.5562, longitude: 77.1, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "GMP", icaoCode: null, faaLid: null, name: "Gimpo International", city: "Seoul", country: "South Korea", countryCode: "KR", region: null, displayName: "Gimpo Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 37.5583, longitude: 126.7906, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HKG", icaoCode: null, faaLid: null, name: "Hong Kong International", city: "Hong Kong", country: "Hong Kong", countryCode: "HK", region: null, displayName: "Hong Kong Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 22.308, longitude: 113.9185, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HGH", icaoCode: null, faaLid: null, name: "Hangzhou Xiaoshan International", city: "Hangzhou", country: "China", countryCode: "CN", region: null, displayName: "Hangzhou Xiaoshan Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 30.2369, longitude: 120.432, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HKT", icaoCode: null, faaLid: null, name: "Phuket International", city: "Phuket", country: "Thailand", countryCode: "TH", region: null, displayName: "Phuket Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 8.1132, longitude: 98.3169, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HND", icaoCode: null, faaLid: null, name: "Haneda", city: "Tokyo", country: "Japan", countryCode: "JP", region: null, displayName: "Haneda Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 35.5494, longitude: 139.7798, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "HYD", icaoCode: null, faaLid: null, name: "Rajiv Gandhi International", city: "Hyderabad", country: "India", countryCode: "IN", region: null, displayName: "Rajiv Gandhi Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 17.2403, longitude: 78.4294, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ICN", icaoCode: null, faaLid: null, name: "Incheon International", city: "Seoul", country: "South Korea", countryCode: "KR", region: null, displayName: "Incheon Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 37.4602, longitude: 126.4407, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "ITM", icaoCode: null, faaLid: null, name: "Itami", city: "Osaka", country: "Japan", countryCode: "JP", region: null, displayName: "Itami Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 34.7855, longitude: 135.4382, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "KIX", icaoCode: null, faaLid: null, name: "Kansai International", city: "Osaka", country: "Japan", countryCode: "JP", region: null, displayName: "Kansai Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 34.4347, longitude: 135.2441, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "KUL", icaoCode: null, faaLid: null, name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY", region: null, displayName: "Kuala Lumpur Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 2.7456, longitude: 101.7072, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MAA", icaoCode: null, faaLid: null, name: "Chennai International", city: "Chennai", country: "India", countryCode: "IN", region: null, displayName: "Chennai Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 12.9941, longitude: 80.1709, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MNL", icaoCode: null, faaLid: null, name: "Ninoy Aquino International", city: "Manila", country: "Philippines", countryCode: "PH", region: null, displayName: "Ninoy Aquino Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 14.5086, longitude: 121.0198, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "NRT", icaoCode: null, faaLid: null, name: "Narita International", city: "Tokyo", country: "Japan", countryCode: "JP", region: null, displayName: "Narita Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 35.7719, longitude: 140.3929, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PEK", icaoCode: null, faaLid: null, name: "Beijing Capital International", city: "Beijing", country: "China", countryCode: "CN", region: null, displayName: "Beijing Capital Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 40.0801, longitude: 116.5846, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PKX", icaoCode: null, faaLid: null, name: "Beijing Daxing International", city: "Beijing", country: "China", countryCode: "CN", region: null, displayName: "Beijing Daxing Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 39.5098, longitude: 116.4105, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PVG", icaoCode: null, faaLid: null, name: "Shanghai Pudong International", city: "Shanghai", country: "China", countryCode: "CN", region: null, displayName: "Shanghai Pudong Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 31.1443, longitude: 121.8083, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SHA", icaoCode: null, faaLid: null, name: "Hongqiao International", city: "Shanghai", country: "China", countryCode: "CN", region: null, displayName: "Hongqiao Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 31.1979, longitude: 121.3363, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SIN", icaoCode: null, faaLid: null, name: "Changi", city: "Singapore", country: "Singapore", countryCode: "SG", region: null, displayName: "Changi Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 1.3644, longitude: 103.9915, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "TPE", icaoCode: null, faaLid: null, name: "Taiwan Taoyuan International", city: "Taipei", country: "Taiwan", countryCode: "TW", region: null, displayName: "Taiwan Taoyuan Intl Airport", globalRegion: "asia", airportClass: "major_commercial", latitude: 25.0797, longitude: 121.2342, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
const oceaniaAirports: SkysirvLiveAirportCatalogEntry[] = [
  // Oceania
  { iataCode: "ADL", icaoCode: null, faaLid: null, name: "Adelaide Airport", city: "Adelaide", country: "Australia", countryCode: "AU", region: null, displayName: "Adelaide Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -34.945, longitude: 138.5306, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "AKL", icaoCode: null, faaLid: null, name: "Auckland Airport", city: "Auckland", country: "New Zealand", countryCode: "NZ", region: null, displayName: "Auckland Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -37.0082, longitude: 174.785, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "BNE", icaoCode: null, faaLid: null, name: "Brisbane Airport", city: "Brisbane", country: "Australia", countryCode: "AU", region: null, displayName: "Brisbane Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -27.3842, longitude: 153.1175, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "CHC", icaoCode: null, faaLid: null, name: "Christchurch Airport", city: "Christchurch", country: "New Zealand", countryCode: "NZ", region: null, displayName: "Christchurch Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -43.4894, longitude: 172.5322, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "MEL", icaoCode: null, faaLid: null, name: "Melbourne Airport", city: "Melbourne", country: "Australia", countryCode: "AU", region: null, displayName: "Melbourne Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -37.669, longitude: 144.841, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "PER", icaoCode: null, faaLid: null, name: "Perth Airport", city: "Perth", country: "Australia", countryCode: "AU", region: null, displayName: "Perth Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -31.9403, longitude: 115.9672, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
  { iataCode: "SYD", icaoCode: null, faaLid: null, name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia", countryCode: "AU", region: null, displayName: "Sydney Kingsford Smith Airport", globalRegion: "oceania", airportClass: "major_commercial", latitude: -33.9399, longitude: 151.1753, priorityRank: 5, isSkysirvLiveEnabled: false, supportsFaa: false, supportsCirium: true, supportsFlightAware: false },
]
export const skysirvLiveAirportCatalog: SkysirvLiveAirportCatalogEntry[] = [
  ...northAmericaAirports,
  ...mexicoCentralAmericaCaribbeanAirports,
  ...southAmericaAirports,
  ...europeAirports,
  ...middleEastAirports,
  ...africaAirports,
  ...asiaAirports,
  ...oceaniaAirports,
]
function normalizeAirportCode(code: string) {
  return code.trim().toUpperCase()
}

function normalizeCountryCode(code: string) {
  return code.trim().toUpperCase()
}

function supportsProvider(
  airport: SkysirvLiveAirportCatalogEntry,
  provider: SkysirvLiveAirportProvider,
) {
  if (provider === "faa") return airport.supportsFaa
  if (provider === "cirium") return airport.supportsCirium
  return airport.supportsFlightAware
}

export function getSkysirvLiveAirportCatalog(
  filters: SkysirvLiveAirportCatalogFilters = {},
) {
  const normalizedCountryCodes = filters.countryCodes?.map(normalizeCountryCode)

  return skysirvLiveAirportCatalog.filter((airport) => {
    if (!filters.includeDisabled && !airport.isSkysirvLiveEnabled) {
      return false
    }

    if (
      filters.globalRegions?.length &&
      !filters.globalRegions.includes(airport.globalRegion)
    ) {
      return false
    }

    if (
      filters.airportClasses?.length &&
      !filters.airportClasses.includes(airport.airportClass)
    ) {
      return false
    }

    if (
      normalizedCountryCodes?.length &&
      !normalizedCountryCodes.includes(normalizeCountryCode(airport.countryCode))
    ) {
      return false
    }

    if (
      filters.providers?.length &&
      !filters.providers.every((provider) => supportsProvider(airport, provider))
    ) {
      return false
    }

    return true
  })
}

export function getSkysirvLiveAirportCodes(
  filters: SkysirvLiveAirportCatalogFilters = {},
) {
  return getSkysirvLiveAirportCatalog(filters).map(
    (airport) => airport.iataCode,
  )
}

export function getSkysirvLiveAirportByCode(code?: string | null) {
  if (!code) return null

  const normalizedCode = normalizeAirportCode(code)

  return (
    skysirvLiveAirportCatalog.find(
      (airport) => normalizeAirportCode(airport.iataCode) === normalizedCode,
    ) ?? null
  )
}

export function getSkysirvLiveAirportCodesByRegion(
  globalRegion: SkysirvLiveGlobalRegion,
  filters: Omit<SkysirvLiveAirportCatalogFilters, "globalRegions"> = {},
) {
  return getSkysirvLiveAirportCodes({
    ...filters,
    globalRegions: [globalRegion],
  })
}

export function getSkysirvLiveAirportCodesByProvider(
  provider: SkysirvLiveAirportProvider,
  filters: Omit<SkysirvLiveAirportCatalogFilters, "providers"> = {},
) {
  return getSkysirvLiveAirportCodes({
    ...filters,
    providers: [provider],
  })
}
